configfile: "config/config.yml"
workdir: config["workdir"]

include: "rules/indexing.smk"
include: "rules/common.smk"
include: "rules/mapping.smk"
include: "rules/call.smk"
include: "rules/extract.smk"
include: "rules/make_bedmethyl_pearson_correlation.smk"

onstart:
    print("\n--- Analysis started ---\n")
onsuccess:
    print("\n--- Workflow finished! ---\n")
onerror:
    print("\n--- An error occurred! ---\n")

rule all:
    input:
        "results/indexes/.continue",
        "results/indexes/gem_indexer.continue",
        expand("results/split/{barcode}/.continue", barcode=BARCODES),
        expand(mapping_patterns, barcode=BARCODES, part=SPLIT),
        expand(merge_patterns, barcode=BARCODES),
        expand(postprocess_patterns, barcode=BARCODES),
        expand("results/get_coverage/{barcode}/.continue", barcode=BARCODES),
        expand("results/get_methylc/{barcode}/.continue", barcode=BARCODES),
        expand(chrom_ctg_bed_pattern, barcode=BARCODES, contig=CONTIGS),
        expand(calling_patterns, barcode=BARCODES, contig=CONTIGS),
        expand("results/calls/{barcode}/.continue", barcode=BARCODES),
        expand("results/extract/{barcode}/.continue", barcode=BARCODES),
        expand("results/extract_signal/{barcode}/.continue", barcode=BARCODES),
        # expand("results/{experiment}_pearson_correlation_qc.csv", experiment=EXPERIMENTS)
