configfile: "config/config.yml"
workdir: config["workdir"]

if config["make_index"] == True:
    include: "rules/indexing_1.smk"
else:
    include: "rules/indexing_2.smk"
    localrules: indexing

include: "rules/common.smk"
include: "rules/mapping.smk"
include: "rules/call.smk"
include: "rules/extract.smk"
include: "rules/make_bedmethyl_pearson_correlation.smk"

onstart:
    print("\n--- Analysis started ---\n")
onsuccess:
    print("\n--- Workflow finished! ---\n")
onerror:
    print("\n--- An error occurred! ---\n")

rule all:
    input:
        "results/indexes/.continue",
        expand(mapping_patterns, barcode=barcodes),
        expand("results/get_coverage/{barcode}/.continue", barcode=barcodes),
        expand("results/get_methylc/{barcode}/.continue", barcode=barcodes),
        expand(chrom_ctg_bed_pattern, barcode=barcodes, contig=CONTIGS),
        expand(calling_patterns, barcode=barcodes, contig=CONTIGS),
        expand("results/calls/{barcode}/.continue", barcode=barcodes),
        expand("results/extract/{barcode}/.continue", barcode=barcodes),
        expand("results/extract_signal/{barcode}/.continue", barcode=barcodes),
        expand("results/{experiment}_pearson_correlation_qc.csv", experiment=experiments)
