executor: slurm
jobs: unlimited

set-resources:
  indexing:
    runtime: 240m
    slurm_partition: 4hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  gem_indexer:
    runtime: 720m
    slurm_partition: 12hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    threads: 52
    cpus_per_task: 52
    mem: 500000MB
  split:
    runtime: 720m
    threads: 6
    cpus_per_task: 6
    slurm_partition: 12hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 62500MB
  mapping:
    runtime: 7200m
    threads: 26
    cpus_per_task: 26
    slurm_partition: 5days
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 250000MB
  merge:
    runtime: 240m
    threads: 13
    cpus_per_task: 13
    slurm_partition: 4hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 12500MB
  postprocess:
    runtime: 720m
    threads: 13
    cpus_per_task: 13
    slurm_partition: 12hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 125000MB
  get_coverage:
    runtime: 240m
    threads: 13
    cpus_per_task: 13
    slurm_partition: 4hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 125000MB
  generate_chrome_ctgs:
    runtime: 240m
    threads: 13
    cpus_per_task: 13
    slurm_partition: 4hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 125000MB
  calling:
    runtime: 240m
    threads: 26
    cpus_per_task: 26
    slurm_partition: 4hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 250000MB
  merge_chroms:
    runtime: 240m
    threads: 26
    cpus_per_task: 26
    slurm_partition: 4hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 250000MB
  gembs_extract:
    runtime: 720m
    threads: 26
    cpus_per_task: 26
    slurm_partition: 12hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 250000MB
  extract_signal:
    runtime: 240m
    threads: 6
    cpus_per_task: 6
    slurm_partition: 4hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 500000MB
  get_methylc:
    runtime: 240m
    threads: 26
    cpus_per_task: 26
    slurm_partition: 4hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 500000MB
  make_bedmethyl_pearson_correlation:
    runtime: 720m
    threads: 52
    cpus_per_task: 52
    slurm_partition: 12hours
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062] --cpu-freq=High-High:Performance"
    mem: 500000MB

use-apptainer: True
apptainer-prefix: workflow/rules/envs
software-deployment-method: apptainer
apptainer-args: -B /data
shadow-prefix: /tmp

# retries: 3
slurm-requeue: False # Prevent jobs from being requeued, otherwise held infinitely
rerun-incomplete: True
keep-going: True
printshellcmds: True

